HW03 completed
pavel-nekrasov/otus_hw pull request #3
Opened 2024-08-21 18:50 UTC by pavel-nekrasov

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-08-22 10:09 UTC, agneum requested changes
Спасибо за выполненное задание. Отличная работа
Однако возвращаю задачу на доработку, потому что не хватает новых юнит-тестов.

Итого: 6 баллов из 10

2024-08-22 10:09 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	sortedWordStatistic []item
Думаю, что третий тип избыточен. Из-за этого в функции `sort` приходится оборачивать слайс перед возвращением. А во-вторых, слайс может быть изменён, и он станет уже не sorted

2024-08-22 10:09 UTC, agneum commented on hw03_frequency_analysis/top_test.go
> +var taskWithAsteriskIsCompleted = true
Не хватает новых юнит-тестов

2024-08-22 10:09 UTC, agneum commented on hw03_frequency_analysis/.golangci.yml
> +run:
Можно (даже лучше) создать один глобальный конфиг линтера, чтобы не дублировать его в каждом задании.

2024-08-23 18:05 UTC, pavel-nekrasov commented on hw03_frequency_analysis/top.go
> +	sortedWordStatistic []item
вы правы. Поправил

2024-08-23 18:06 UTC, pavel-nekrasov commented on hw03_frequency_analysis/top_test.go
> +var taskWithAsteriskIsCompleted = true
исправил

2024-08-23 18:09 UTC, pavel-nekrasov commented on hw03_frequency_analysis/.golangci.yml
> +run:
он существует в корневой папке заданий.  и если локальный убрать - то будет ругаться на github.com/stretchr/testify/require.  Я просто не хотел бы его трогать до поры до времени, потому что не со всеми настройками разобрался.  Давайте я в след задаче доведу его до ума.

2024-08-25 03:33 UTC, agneum approved these changes
Спасибо за правки.
10/10. Принято

2024-08-30 14:13 UTC, merged